require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.3
  NewCops: enable
  Exclude:
    - db/**/*
    - bin/*
    - node_modules/**/*
    - .simplecov
    - tmp/**/*
    - vendor/**/*
    - cypress/**/*
    - lib/templates/**/*
    - spec/support/webmock.rb

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Lint/MissingSuper:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/PredicateName:
  AllowedMethods:
    - is_a?

Naming/VariableNumber:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

RSpec/NestedGroups:
  Max: 10

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
